version: '3.8'

networks:
  web_network:
    external: true
  internal_db_net:
    driver: bridge

services:
  # --- Database ---
  sasipca-db:
    image: mariadb:latest
    container_name: sasipca-db
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: sasipca
    volumes:
      - /home/areal/docker/sasipca/db_data:/var/lib/mysql
    networks:
      - internal_db_net
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "${DB_APIUSER_NAME}", "--password=${DB_APIUSER_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 20s

  # --- API ---
  sasipca-api:
    build: .
    image: sasipca-api:latest
    container_name: sasipca-api
    restart: unless-stopped
    dns:
      - 1.1.1.1
      - 8.8.8.8
    depends_on:
      sasipca-db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
      - DB_CONNECTION_KEY=${DB_CONNECTION_KEY}
      - JWT_KEY=${JWT_KEY}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
    volumes:
      - /home/areal/docker/sasipca/storage:/app/Storage
      - ${FIREBASE_JSON_LOCAL_PATH}:/app/sasipca-2ea18-firebase-adminsdk-fbsvc-5d72cf6e66.json
    networks:
      - web_network
      - internal_db_net