version: '3.8'

networks:
  web_network:
    external: true
  internal_db_net:
    driver: bridge

services:
  # --- Database ---
  sasipca-db:
    image: mariadb:latest
    container_name: sasipca-db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD} # Variable from Portainer
      MARIADB_DATABASE: sasipca
    volumes:
      - /home/areal/docker/sasipca/db_data:/var/lib/mysql
    networks:
      - internal_db_net
    ports:
      - "3306:3306"

  # --- API ---
  sasipca-api:
    build: .  # Builds from the repo root
    container_name: sasipca-api
    restart: unless-stopped
    depends_on:
      - sasipca-db
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
      - DB_CONNECTION_KEY=${DB_CONNECTION_KEY}
      - JWT_KEY=${JWT_KEY}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
    volumes:
      # Storage persistence
      - /home/areal/docker/sasipca/storage:/app/Storage
    networks:
      - web_network
      - internal_db_net