// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sasipca_API.Data;

#nullable disable

namespace sasipca_API.Migrations
{
    [DbContext(typeof(NLDbContext))]
    [Migration("20250323215523_HangfireMigration")]
    partial class HangfireMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ImagemProduto", b =>
                {
                    b.Property<int>("IdImagem")
                        .HasColumnType("int")
                        .HasColumnName("id_imagem")
                        .HasComment("ID da Imagem.");

                    b.Property<int>("IdProduto")
                        .HasColumnType("int")
                        .HasColumnName("id_produto")
                        .HasComment("ID do Produto ao qual a imagem reflete.");

                    b.HasKey("IdImagem", "IdProduto");

                    b.HasIndex("IdProduto");

                    b.ToTable("imagem_produto", (string)null);
                });

            modelBuilder.Entity("ImagemServico", b =>
                {
                    b.Property<int>("IdImagem")
                        .HasColumnType("int")
                        .HasColumnName("id_imagem")
                        .HasComment("ID da imagem");

                    b.Property<int>("IdServico")
                        .HasColumnType("int")
                        .HasColumnName("id_servico")
                        .HasComment("ID do Serviço ao qual a imagem corresponde");

                    b.HasKey("IdImagem", "IdServico");

                    b.HasIndex("IdServico");

                    b.ToTable("imagem_servico", (string)null);
                });

            modelBuilder.Entity("sasipca_API.Models.Avaliacao", b =>
                {
                    b.Property<int>("IdAvaliacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_avaliacao");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAvaliacao"));

                    b.Property<DateTime>("DataAvaliacao")
                        .HasColumnType("datetime")
                        .HasColumnName("data_avaliacao")
                        .HasComment("Nota dada a um serviço de 1 a 5.");

                    b.Property<int>("IdUtilizador")
                        .HasColumnType("int")
                        .HasColumnName("id_utilizador")
                        .HasComment("Data/Hora que a avaliação foi criada.");

                    b.Property<int>("IdUtilizadorNavigationIdPessoa")
                        .HasColumnType("int");

                    b.Property<int>("Nota")
                        .HasColumnType("int")
                        .HasColumnName("nota")
                        .HasComment("Utilizador que fez a avaliação.");

                    b.HasKey("IdAvaliacao");

                    b.HasIndex("IdUtilizadorNavigationIdPessoa");

                    b.ToTable("avaliacao", (string)null);
                });

            modelBuilder.Entity("sasipca_API.Models.CategoriasProduto", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_categoria");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("Nome")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nome")
                        .HasComment("Nome da categoria.");

                    b.HasKey("IdCategoria")
                        .HasName("PK_categoria");

                    b.ToTable("categorias_produtos", (string)null);
                });

            modelBuilder.Entity("sasipca_API.Models.CodigoPostal", b =>
                {
                    b.Property<string>("IdCodPostal")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("id_cod_postal")
                        .HasComment("O próprio código postal");

                    b.Property<string>("Localidade")
                        .IsRequired()
                        .HasMaxLength(75)
                        .IsUnicode(false)
                        .HasColumnType("varchar(75)")
                        .HasColumnName("localidade")
                        .HasComment("Localidade ao qual o código-postal corresponde.");

                    b.HasKey("IdCodPostal");

                    b.ToTable("codigo_postal", (string)null);
                });

            modelBuilder.Entity("sasipca_API.Models.EstadoEvento", b =>
                {
                    b.Property<int>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstado"));

                    b.Property<string>("TipoEstado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tipo_estado")
                        .HasComment("Tipo de estado de um evento.");

                    b.HasKey("IdEstado");

                    b.ToTable("estado_evento", (string)null);
                });

            modelBuilder.Entity("sasipca_API.Models.EstadoProduto", b =>
                {
                    b.Property<int>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstado"));

                    b.Property<string>("TipoEstado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tipo_estado")
                        .HasComment("Tipo de estado de um produto.");

                    b.HasKey("IdEstado");

                    b.ToTable("estado_produto", (string)null);
                });

            modelBuilder.Entity("sasipca_API.Models.EstadoProposta", b =>
                {
                    b.Property<int>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstado"));

                    b.Property<string>("TipoEstado")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tipo_estado")
                        .HasComment("Descrição do estado da proposta.");

                    b.HasKey("IdEstado")
                        .HasName("PK_proposta_estado");

                    b.ToTable("estado_proposta", (string)null);
                });

            modelBuilder.Entity("sasipca_API.Models.EstadoServico", b =>
                {
                    b.Property<int>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstado"));

                    b.Property<string>("TipoEstado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tipo_estado")
                        .HasComment("Tipo de estado de um serviço.");

                    b.HasKey("IdEstado");

                    b.ToTable("estado_servico", (string)null);
                });

            modelBuilder.Entity("sasipca_API.Models.Evento", b =>
                {
                    b.Property<int>("IdEvento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_evento");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEvento"));

                    b.Property<DateTime>("DataIni")
                        .HasColumnType("datetime")
                        .HasColumnName("data_ini")
                        .HasComment("Data/Hora de início do evento.");

                    b.Property<string>("Descricao")
                        .HasMaxLength(400)
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)")
                        .HasColumnName("descricao")
                        .HasComment("Descrição do evento");

                    b.Property<int>("IdCriador")
                        .HasColumnType("int")
                        .HasColumnName("id_criador")
                        .HasComment("ID do estado do momento do evento.");

                    b.Property<int?>("IdEstado")
                        .HasColumnType("int")
                        .HasColumnName("id_estado")
                        .HasComment("ID da pessoa que criou o evento");

                    b.Property<string>("Morada")
                        .IsRequired()
                        .HasMaxLength(75)
                        .IsUnicode(false)
                        .HasColumnType("varchar(75)")
                        .HasColumnName("morada")
                        .HasComment("Localização onde o evento decorre");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(75)
                        .IsUnicode(false)
                        .HasColumnType("varchar(75)")
                        .HasColumnName("nome")
                        .HasComment("Nome/Título do Evento");

                    b.Property<int>("NumMinPessoas")
                        .HasColumnType("int")
                        .HasColumnName("num_min_pessoas")
                        .HasComment("Requisito de número mínimo de pessoas para o evento ocorrer");

                    b.HasKey("IdEvento")
                        .HasName("PK_Evento");

                    b.HasIndex("IdCriador");

                    b.HasIndex("IdEstado");

                    b.ToTable("evento", (string)null);
                });

            modelBuilder.Entity("sasipca_API.Models.Imagem", b =>
                {
                    b.Property<int>("IdImagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_imagem");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdImagem"));

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("url")
                        .HasComment("Link da imagem, guardado na conta de armazenamento Azure.");

                    b.HasKey("IdImagem");

                    b.ToTable("imagens", (string)null);
                });

            modelBuilder.Entity("sasipca_API.Models.InscricaoEvento", b =>
                {
                    b.Property<int>("IdInscricao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_inscricao");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInscricao"));

                    b.Property<DateTime>("DataInscricao")
                        .HasColumnType("datetime")
                        .HasColumnName("data_inscricao")
                        .HasComment("Data/Hora da inscrição a este evento.");

                    b.Property<int>("IdEvento")
                        .HasColumnType("int")
                        .HasColumnName("id_evento")
                        .HasComment("ID do evento ao qual a pessoa se inscreve.");

                    b.Property<int>("IdItem")
                        .HasColumnType("int")
                        .HasColumnName("id_item")
                        .HasComment("ID do item selecionado para a inscrição.");

                    b.Property<int>("IdPessoa")
                        .HasColumnType("int")
                        .HasColumnName("id_pessoa")
                        .HasComment("ID da pessoa à qual esta inscrição se aplica");

                    b.HasKey("IdInscricao");

                    b.HasIndex("IdEvento");

                    b.HasIndex("IdItem");

                    b.HasIndex(new[] { "IdPessoa", "IdEvento" }, "uc_pessoa_evento")
                        .IsUnique();

                    b.ToTable("inscricao_evento", null, t =>
                        {
                            t.HasComment("Registos de inscrição de pessoas a eventos, especificando também o item que selecionou para levar.");
                        });
                });

            modelBuilder.Entity("sasipca_API.Models.ItemNecessarioEvento", b =>
                {
                    b.Property<int>("IdItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_item");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdItem"));

                    b.Property<int>("IdEvento")
                        .HasColumnType("int")
                        .HasColumnName("id_evento")
                        .HasComment("Evento ao qual este item pertence.");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome")
                        .HasComment("Nome do item.");

                    b.Property<int?>("Quantidade")
                        .HasColumnType("int")
                        .HasColumnName("quantidade")
                        .HasComment("Quantidade necessária deste item para este evento.");

                    b.HasKey("IdItem");

                    b.HasIndex("IdEvento");

                    b.ToTable("item_necessario_evento", (string)null);
                });

            modelBuilder.Entity("sasipca_API.Models.ModalidadePreco", b =>
                {
                    b.Property<int>("IdModalidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_modalidade");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdModalidade"));

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tipo")
                        .HasComment("Se o pagamento de um serviço é Total/Hora/Outros.");

                    b.HasKey("IdModalidade");

                    b.ToTable("modalidade_preco", (string)null);
                });

            modelBuilder.Entity("sasipca_API.Models.Pessoa", b =>
                {
                    b.Property<int>("IdPessoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_pessoa");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPessoa"));

                    b.Property<string>("Contacto")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("contacto")
                        .HasComment("Contacto Telefónico da pessoa.");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email")
                        .HasComment("Endereço de E-Mail da pessoa.");

                    b.Property<string>("IdCodPostal")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("id_cod_postal")
                        .HasComment("Código Postal da pessoa.");

                    b.Property<string>("Morada")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("morada")
                        .HasComment("Morada da pessoa.");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("nome")
                        .HasComment("Nome da pessoa.");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("password")
                        .HasComment("Palavra-Passe encriptada por SHA-256 da pessoa.");

                    b.HasKey("IdPessoa")
                        .HasName("PK_Utilizadores");

                    b.HasIndex("IdCodPostal");

                    b.HasIndex(new[] { "Email" }, "IDX_Pessoa_Email");

                    b.HasIndex(new[] { "Email" }, "UQ_email")
                        .IsUnique();

                    b.ToTable("pessoa", null, t =>
                        {
                            t.HasComment("Tabela para utilizadores.");
                        });
                });

            modelBuilder.Entity("sasipca_API.Models.Produto", b =>
                {
                    b.Property<int>("IdProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_produto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProduto"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(400)
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)")
                        .HasColumnName("descricao")
                        .HasComment("Descrição de produto.");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int")
                        .HasColumnName("id_categoria")
                        .HasComment("ID da categoria ao qual este produto pertence.");

                    b.Property<int?>("IdEstado")
                        .HasColumnType("int")
                        .HasColumnName("id_estado")
                        .HasComment("ID Referente ao estado atual do produto");

                    b.Property<int>("IdVendedor")
                        .HasColumnType("int")
                        .HasColumnName("id_vendedor")
                        .HasComment("ID da pessoa que fez o anúncio / está a vender");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(75)
                        .IsUnicode(false)
                        .HasColumnType("varchar(75)")
                        .HasColumnName("nome")
                        .HasComment("Nome de Produto.");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("preco")
                        .HasComment("Preço do produto.");

                    b.HasKey("IdProduto")
                        .HasName("PK_Produto");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdVendedor");

                    b.ToTable("produto", (string)null);
                });

            modelBuilder.Entity("sasipca_API.Models.PropostaProduto", b =>
                {
                    b.Property<int>("IdPropostaProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_proposta_produto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPropostaProduto"));

                    b.Property<int>("IdComprador")
                        .HasColumnType("int")
                        .HasColumnName("id_comprador")
                        .HasComment("ID da pessoa a fazer a proposta.");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int")
                        .HasColumnName("id_estado")
                        .HasComment("ID do estado atual da proposta.");

                    b.Property<int>("IdProduto")
                        .HasColumnType("int")
                        .HasColumnName("id_produto")
                        .HasComment("ID do produto a ter proposta");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("valor")
                        .HasComment("Valor dado pelo comprador.");

                    b.HasKey("IdPropostaProduto");

                    b.HasIndex("IdComprador");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdProduto");

                    b.ToTable("proposta_produto", (string)null);
                });

            modelBuilder.Entity("sasipca_API.Models.PropostaServico", b =>
                {
                    b.Property<int>("IdPropostaServico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_proposta_servico");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPropostaServico"));

                    b.Property<int>("IdEstado")
                        .HasColumnType("int")
                        .HasColumnName("id_estado")
                        .HasComment("ID do estado atual da proposta.");

                    b.Property<int>("IdExecutor")
                        .HasColumnType("int")
                        .HasColumnName("id_executor")
                        .HasComment("ID da pessoa a fazer a proposta.");

                    b.Property<int>("IdServico")
                        .HasColumnType("int")
                        .HasColumnName("id_servico")
                        .HasComment("ID do serviço a ter proposta");

                    b.HasKey("IdPropostaServico");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdExecutor");

                    b.HasIndex("IdServico");

                    b.ToTable("proposta_servico", (string)null);
                });

            modelBuilder.Entity("sasipca_API.Models.Servico", b =>
                {
                    b.Property<int>("IdServico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_servico");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdServico"));

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime")
                        .HasColumnName("data_fim")
                        .HasComment("Data/Hora de fim do Serviço (opcional)");

                    b.Property<DateTime>("DataIni")
                        .HasColumnType("datetime")
                        .HasColumnName("data_ini")
                        .HasComment("Data/Hora para o Início do Serviço");

                    b.Property<string>("Descricao")
                        .HasMaxLength(400)
                        .IsUnicode(false)
                        .HasColumnType("varchar(400)")
                        .HasColumnName("descricao")
                        .HasComment("Descrição do Serviço");

                    b.Property<int?>("IdAvaliacao")
                        .HasColumnType("int")
                        .HasColumnName("id_avaliacao")
                        .HasComment("ID da avaliação dada a este serviço.");

                    b.Property<int>("IdCriador")
                        .HasColumnType("int")
                        .HasColumnName("id_criador")
                        .HasComment("ID da pessoa que criou o serviço.");

                    b.Property<int?>("IdEstado")
                        .HasColumnType("int")
                        .HasColumnName("id_estado")
                        .HasComment("ID do estado no qual o serviço se encontra.");

                    b.Property<int?>("IdExecutor")
                        .HasColumnType("int")
                        .HasColumnName("id_executor")
                        .HasComment("ID da pessoa que executou o serviço. Nulo porque quando o registo é criado ainda não existe propostas.");

                    b.Property<int>("IdModalidadePreco")
                        .HasColumnType("int")
                        .HasColumnName("id_modalidadepreco")
                        .HasComment("ID do tipo da modalidade de pagamento deste serviço (Hora/Totall)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(75)
                        .IsUnicode(false)
                        .HasColumnType("varchar(75)")
                        .HasColumnName("nome")
                        .HasComment("Nome/Título do Serviço");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("preco")
                        .HasComment("Preço do Serviço (Por Hora/Total).");

                    b.HasKey("IdServico")
                        .HasName("PK_Servico");

                    b.HasIndex("IdAvaliacao");

                    b.HasIndex("IdCriador");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdExecutor");

                    b.HasIndex("IdModalidadePreco");

                    b.ToTable("servico", (string)null);
                });

            modelBuilder.Entity("ImagemProduto", b =>
                {
                    b.HasOne("sasipca_API.Models.Imagem", null)
                        .WithMany()
                        .HasForeignKey("IdImagem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_produto_imagens");

                    b.HasOne("sasipca_API.Models.Produto", null)
                        .WithMany()
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_imagem_produto");
                });

            modelBuilder.Entity("ImagemServico", b =>
                {
                    b.HasOne("sasipca_API.Models.Imagem", null)
                        .WithMany()
                        .HasForeignKey("IdImagem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_servico_imagens");

                    b.HasOne("sasipca_API.Models.Servico", null)
                        .WithMany()
                        .HasForeignKey("IdServico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_imagem_servico");
                });

            modelBuilder.Entity("sasipca_API.Models.Avaliacao", b =>
                {
                    b.HasOne("sasipca_API.Models.Pessoa", "IdUtilizadorNavigation")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("IdUtilizadorNavigationIdPessoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdUtilizadorNavigation");
                });

            modelBuilder.Entity("sasipca_API.Models.Evento", b =>
                {
                    b.HasOne("sasipca_API.Models.Pessoa", "IdCriadorNavigation")
                        .WithMany("Eventos")
                        .HasForeignKey("IdCriador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_evento_pessoa");

                    b.HasOne("sasipca_API.Models.EstadoEvento", "IdEstadoNavigation")
                        .WithMany("Eventos")
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_evento_estado");

                    b.Navigation("IdCriadorNavigation");

                    b.Navigation("IdEstadoNavigation");
                });

            modelBuilder.Entity("sasipca_API.Models.InscricaoEvento", b =>
                {
                    b.HasOne("sasipca_API.Models.Evento", "IdEventoNavigation")
                        .WithMany("InscricaoEventos")
                        .HasForeignKey("IdEvento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_inscricao_evento");

                    b.HasOne("sasipca_API.Models.ItemNecessarioEvento", "IdItemNavigation")
                        .WithMany("InscricaoEventos")
                        .HasForeignKey("IdItem")
                        .IsRequired()
                        .HasConstraintName("FK_inscricao_item");

                    b.HasOne("sasipca_API.Models.Pessoa", "IdPessoaNavigation")
                        .WithMany("InscricaoEventos")
                        .HasForeignKey("IdPessoa")
                        .IsRequired()
                        .HasConstraintName("FK_inscricao_pessoa");

                    b.Navigation("IdEventoNavigation");

                    b.Navigation("IdItemNavigation");

                    b.Navigation("IdPessoaNavigation");
                });

            modelBuilder.Entity("sasipca_API.Models.ItemNecessarioEvento", b =>
                {
                    b.HasOne("sasipca_API.Models.Evento", "IdEventoNavigation")
                        .WithMany("ItemNecessarioEventos")
                        .HasForeignKey("IdEvento")
                        .IsRequired()
                        .HasConstraintName("FK_item_necessario_evento");

                    b.Navigation("IdEventoNavigation");
                });

            modelBuilder.Entity("sasipca_API.Models.Pessoa", b =>
                {
                    b.HasOne("sasipca_API.Models.CodigoPostal", "IdCodPostalNavigation")
                        .WithMany("Pessoas")
                        .HasForeignKey("IdCodPostal")
                        .HasConstraintName("FK_pessoa_codpostal");

                    b.Navigation("IdCodPostalNavigation");
                });

            modelBuilder.Entity("sasipca_API.Models.Produto", b =>
                {
                    b.HasOne("sasipca_API.Models.CategoriasProduto", "IdCategoriaNavigation")
                        .WithMany("Produtos")
                        .HasForeignKey("IdCategoria")
                        .IsRequired()
                        .HasConstraintName("FK_produto_categorias");

                    b.HasOne("sasipca_API.Models.EstadoProduto", "IdEstadoNavigation")
                        .WithMany("Produtos")
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_produto_estado");

                    b.HasOne("sasipca_API.Models.Pessoa", "IdVendedorNavigation")
                        .WithMany("Produtos")
                        .HasForeignKey("IdVendedor")
                        .IsRequired()
                        .HasConstraintName("FK_produto_vendedor");

                    b.Navigation("IdCategoriaNavigation");

                    b.Navigation("IdEstadoNavigation");

                    b.Navigation("IdVendedorNavigation");
                });

            modelBuilder.Entity("sasipca_API.Models.PropostaProduto", b =>
                {
                    b.HasOne("sasipca_API.Models.Pessoa", "IdCompradorNavigation")
                        .WithMany("PropostaProdutos")
                        .HasForeignKey("IdComprador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_proposta_comprador");

                    b.HasOne("sasipca_API.Models.EstadoProposta", "IdEstadoNavigation")
                        .WithMany("PropostaProdutos")
                        .HasForeignKey("IdEstado")
                        .IsRequired()
                        .HasConstraintName("FK_proposta_estado");

                    b.HasOne("sasipca_API.Models.Produto", "IdProdutoNavigation")
                        .WithMany("PropostaProdutos")
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_proposta_produto");

                    b.Navigation("IdCompradorNavigation");

                    b.Navigation("IdEstadoNavigation");

                    b.Navigation("IdProdutoNavigation");
                });

            modelBuilder.Entity("sasipca_API.Models.PropostaServico", b =>
                {
                    b.HasOne("sasipca_API.Models.EstadoProposta", "IdEstadoNavigation")
                        .WithMany("PropostaServicos")
                        .HasForeignKey("IdEstado")
                        .IsRequired()
                        .HasConstraintName("FK_proposta_estado");

                    b.HasOne("sasipca_API.Models.Pessoa", "IdExecutorNavigation")
                        .WithMany("PropostaServicos")
                        .HasForeignKey("IdExecutor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_proposta_executor");

                    b.HasOne("sasipca_API.Models.Servico", "IdServicoNavigation")
                        .WithMany("PropostaServicos")
                        .HasForeignKey("IdServico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_proposta_servico");

                    b.Navigation("IdEstadoNavigation");

                    b.Navigation("IdExecutorNavigation");

                    b.Navigation("IdServicoNavigation");
                });

            modelBuilder.Entity("sasipca_API.Models.Servico", b =>
                {
                    b.HasOne("sasipca_API.Models.Avaliacao", "IdAvaliacaoNavigation")
                        .WithMany("Servicos")
                        .HasForeignKey("IdAvaliacao")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_servico_avaliacao");

                    b.HasOne("sasipca_API.Models.Pessoa", "IdCriadorNavigation")
                        .WithMany("ServicoIdCriadorNavigations")
                        .HasForeignKey("IdCriador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_servico_criador");

                    b.HasOne("sasipca_API.Models.EstadoServico", "IdEstadoNavigation")
                        .WithMany("Servicos")
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_servico_estado_servico");

                    b.HasOne("sasipca_API.Models.Pessoa", "IdExecutorNavigation")
                        .WithMany("ServicoIdExecutorNavigations")
                        .HasForeignKey("IdExecutor")
                        .HasConstraintName("FK_servico_executor");

                    b.HasOne("sasipca_API.Models.ModalidadePreco", "IdModalidadePrecoNavigation")
                        .WithMany("Servicos")
                        .HasForeignKey("IdModalidadePreco")
                        .IsRequired()
                        .HasConstraintName("FK_servico_modalidade_preco");

                    b.Navigation("IdAvaliacaoNavigation");

                    b.Navigation("IdCriadorNavigation");

                    b.Navigation("IdEstadoNavigation");

                    b.Navigation("IdExecutorNavigation");

                    b.Navigation("IdModalidadePrecoNavigation");
                });

            modelBuilder.Entity("sasipca_API.Models.Avaliacao", b =>
                {
                    b.Navigation("Servicos");
                });

            modelBuilder.Entity("sasipca_API.Models.CategoriasProduto", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("sasipca_API.Models.CodigoPostal", b =>
                {
                    b.Navigation("Pessoas");
                });

            modelBuilder.Entity("sasipca_API.Models.EstadoEvento", b =>
                {
                    b.Navigation("Eventos");
                });

            modelBuilder.Entity("sasipca_API.Models.EstadoProduto", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("sasipca_API.Models.EstadoProposta", b =>
                {
                    b.Navigation("PropostaProdutos");

                    b.Navigation("PropostaServicos");
                });

            modelBuilder.Entity("sasipca_API.Models.EstadoServico", b =>
                {
                    b.Navigation("Servicos");
                });

            modelBuilder.Entity("sasipca_API.Models.Evento", b =>
                {
                    b.Navigation("InscricaoEventos");

                    b.Navigation("ItemNecessarioEventos");
                });

            modelBuilder.Entity("sasipca_API.Models.ItemNecessarioEvento", b =>
                {
                    b.Navigation("InscricaoEventos");
                });

            modelBuilder.Entity("sasipca_API.Models.ModalidadePreco", b =>
                {
                    b.Navigation("Servicos");
                });

            modelBuilder.Entity("sasipca_API.Models.Pessoa", b =>
                {
                    b.Navigation("Avaliacoes");

                    b.Navigation("Eventos");

                    b.Navigation("InscricaoEventos");

                    b.Navigation("Produtos");

                    b.Navigation("PropostaProdutos");

                    b.Navigation("PropostaServicos");

                    b.Navigation("ServicoIdCriadorNavigations");

                    b.Navigation("ServicoIdExecutorNavigations");
                });

            modelBuilder.Entity("sasipca_API.Models.Produto", b =>
                {
                    b.Navigation("PropostaProdutos");
                });

            modelBuilder.Entity("sasipca_API.Models.Servico", b =>
                {
                    b.Navigation("PropostaServicos");
                });
#pragma warning restore 612, 618
        }
    }
}
